### ISSUE TITLE
How to use this library

### ISSUE THREAD

**Issue by dev-bre** [lemmy/skype4java#1]
Hi,
it could be great to use Skype4Java on linux, and I hope that with your library it will be possible, but I tried to use the jar file under lib folder, but it is broken,..... could please tell me how to use this library on linux ubuntu? thanks.

**Comment by lemmy** [comment]
What do you mean by broken? Does it throw an exception?

**Comment by dev-bre** [comment]
It is just to understand how to use it... I imported the jar inside my project, but Eclipse says thet packages related to Skype, are unknown... and it doesn't compile...
Could you please tell me also if it works for Windows and Mac as well?
thanks.

**Comment by lemmy** [comment]
I haven't checked if it works with Mac or Windows and my gut feeling is, that it won't because of missing DBus support.

**Comment by sasikrishna** [comment]
Hi lemmy,
               very thanks for skype linux dbus library. I am using your classes for my  skype desktop client. I wrote below code to connect to skype but mostly am getting below error, sometimes it is working fine..

## Program:

```
    Skype skype = new Skype("xxxxxx", "xxxxxx");
    LinuxDBusConnector dbusConnector = new LinuxDBusConnector(skype, "xxxxxx", "xxxxxx");

     ChatMessageListener chatMessageListener = new ChatMessageListener() {

        public void chatMessageSent(ChatMessage sentChatMessage) throws SkypeException {
            // TODO Auto-generated method stub
            System.out.println("Sent Chat Message " + sentChatMessage.getContent());
        }

        public void chatMessageReceived(ChatMessage receivedChatMessage) throws SkypeException {
            // TODO Auto-generated method stub
            System.out.println("Received Chat Message " + receivedChatMessage.getContent());
        }
    };

    skype.addChatMessageListener(chatMessageListener);
```

## Error:

Set status to PENDING_AUTHORIZATION for skype instance: com.skype.Skype@1dc778e
Set status to NOT_AVAILABLE for skype instance: com.skype.Skype@1dc778e
Exception in thread "main" com.skype.NotAttachedException
    at com.skype.Utils.convertToSkypeException(Utils.java:57)
    at com.skype.Utils.getProperty(Utils.java:138)
    at com.skype.Profile.getProperty(Profile.java:646)
    at com.skype.Profile.getCountry(Profile.java:334)
    at com.test.TestSkype.main(TestSkype.java:31)
Caused by: com.skype.connector.NotAttachedException
    at com.skype.connector.Connector.assureAttached(Connector.java:630)
    at com.skype.connector.Connector.execute(Connector.java:554)
    at com.skype.connector.Connector.execute(Connector.java:521)
    at com.skype.connector.Connector.execute(Connector.java:492)
    at com.skype.connector.Connector.execute(Connector.java:465)
    at com.skype.Utils.getProperty(Utils.java:134)
    ... 3 more

Is this the correct approach or can u provide me an basic tutorial how to connect skype client

Thanks in advance
Sasi

**Comment by lemmy** [comment]
"PENDING_AUTHORIZATION" indicates that the Skype instance waits for user input if the connection coming from skype4java should be accepted. Look for a dialog asking to grant permissions.

**Comment by sasikrishna** [comment]
Very rarely skype dialog prompting for permissions. Most of times when i executed program it is showing below error.

Error:
Exception in thread "main" com.skype.NotAttachedException and skype connector status set to NOT_AVAiLABLE

**Comment by lemmy** [comment]
What Skype version are you on? Older versions used to show the prompt only once and then never again. Does anything show up on Options > Public API in Skype?

**Comment by sasikrishna** [comment]
My Skype version 4.1.0.2. Now updated to 4.2 but still the problem not fixed. When allowing permissions if am checking Remember this selection checkbox, client name showing in Public API in Skype options. If i just allowed permissions with unchecking the box no name is showing in the options....

Now also very rarely D Bus is connecting to Skype desktop client. Most of times getting above err.

**Comment by lemmy** [comment]
Try an older version of Skype (2.x) which I used back when I worked on skype4java.

**Comment by sasikrishna** [comment]
Uninstalled current version and installed Skype 2.x ver...Nothing changed some times connecting, rest of times throwing exception. 

My sample pasted above is correct?

**Comment by lemmy** [comment]
Check out https://github.com/lemmy/kraken-gateway/tree/master/src/java/net/sf/kraken/protocols/skype/ to see how I used skype4java in kraken-gateway.

Note that I do not use skype4java myself anymore and thus can only offer limited help.

**Comment by sasikrishna** [comment]
You helped me alot....

Many Thanks Lemmy..

**Comment by sasikrishna** [comment]
Hi  lemmy,
    Can u clear me this doubt. Why do we are login into skype using pipe login command rather than getting the existing skype process.

**Comment by lemmy** [comment]
Correct me if I am wrong, but AFAIK this is not possible with Skype's dbus API

**Comment by sasikrishna** [comment]
It's possible with existing Skype process. You no need to provide any credentials and to create new skype process. We must sign in before starting our application.

Strange thing is that when am running your application & my application( uses same DBus but not wrapper classes) simultaneously, your app getting all the notifications but my app doesn't.
