### ISSUE TITLE
Skype for Java throws exception while using in Group Chat

### ISSUE THREAD

**Issue by sandeeprock12** [lemmy/skype4java#2]
I have been Skype for Java API successfully in singular chats. But, I am getting an exception while using it in Group Chat. Below is the exception:

com.skype.CommandFailedException: Invalid/uknown chat name given
at com.skype.Utils.checkError(Utils.java:77)
at com.skype.Chat.send(Chat.java:275)
at skypePackage.MyListener.myListener(MyListener.java:85)
at skypePackage.MyListener.chatMessageReceived(MyListener.java:220)
at com.skype.ChatMessageConnectorListener.fireMessageReceived(ChatMessageConnectorListener.java:58)
at com.skype.ChatMessageConnectorListener.messageReceived(ChatMessageConnectorListener.java:38)
at com.skype.connector.Connector.fireMessageEvent(Connector.java:1119)
at com.skype.connector.Connector.access$500(Connector.java:37)
at com.skype.connector.Connector$13.run(Connector.java:1098)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)

Please help!

**Comment by lemmy** [comment]
Sorry, I'm not using Skype or this software anymore. You thus have to fork and fix yourself.

**Comment by sandeeprock12** [comment]
Thanks lemmy!
